[project]
name = "TC-DNA"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "customtkinter>=5.2.2",
    "darkdetect>=0.8.0",
    "packaging>=25.0",
    "psutil>=7.1.3",
    "pywin32>=311",
]
